name: aps_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.5.1
  camera: ^0.8.1
  cloud_firestore: ^1.0.6
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.1
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.5
  flutter_absolute_path: ^1.0.6
  flutter_email_sender: ^5.0.0
  flutter_spinkit: ^5.0.0
  intl: ^0.17.0
  keyboard_visibility: ^0.5.6
  multi_image_picker: ^4.8.0
  permission_handler: ^7.1.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/chat.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/chat.png
