name: aps_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/chat.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/chat.png